---

################################################################################
# BEGIN Prereqs
- name: install elastic rpm key
  rpm_key:
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: setup elastic yum repo
  copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install prereqs
  yum:
    name:
      - "java-1.8.0-openjdk"
      - "httpd"
      - "httpd-tools"
      - "firewalld"
      - "python-firewall"
    state: present

- name: start/enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

# END Prereqs
################################################################################

################################################################################
# BEGIN Elasticsearch
- name: install elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: sysconfig elasticsearch
  copy:
    src: "elasticsearch.sysconf"
    dest: "/etc/sysconfig/elasticsearch"
  notify: restart elasticsearch

- name: configure elasticsearch
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
  notify: restart elasticsearch

- name: setup geoip plugin
  shell: "/usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip -s && touch /usr/local/ingest-geoip-installed"
  args:
    stdin: 'y'
    creates: "/usr/local/ingest-geoip-installed"
  register: output
  failed_when: output.rc != 0
  changed_when: False

- name: start and enable elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true

# END Elasticsearch
################################################################################


################################################################################
# BEGIN Logstash
- name: install logstash
  yum:
    name: "logstash"
    state: present

- name: start logstash
  service:
    name: logstash
    state: started
    enabled: true
# END Logstash
################################################################################


################################################################################
# BEGIN Kibana
- name: install kibana
  yum:
    name: "kibana"
    state: present

- name: configure kibana
  template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
  notify: restart kibana

- name: start kibana
  service:
    name: kibana
    state: started
    enabled: true

- name: allow port 5601
  firewalld:
    port: 5601/tcp
    state: enabled
    permanent: true
    immediate: true

- name: wait for kibana to be up
  wait_for:
    host: "{{kb_server_host}}"
    port: 5601
# END Kibana
################################################################################

################################################################################
# BEGIN Filebeat
- name: install filebeat
  yum:
    name: "filebeat"
    state: present

- name: configure filebeat
  template:
    src: "filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
  notify: restart filebeat

- name: enable system filebeat
  shell: "filebeat modules enable system && touch /usr/local/filebeat-system-module-enabled"
  args:
    creates: "/usr/local/filebeat-system-module-enabled"
  register: output
  failed_when: output.rc != 0
  changed_when: False

- name: setup filebeat
  shell: "filebeat setup && touch /usr/local/filebeat-setup"
  args:
    creates: "/usr/local/filebeat-setup"
  register: output
  failed_when: output.rc != 0
  changed_when: False

- name: setup filebeat dashboards
  shell: "filebeat setup -e -E output.logstash.enabled=false -E output.elasticsearch.hosts=['localhost:9200'] setup.kibana.host={{kb_server_host}}:5601 &&  touch /usr/local/filebeat-setup-dashboards"
  args:
    creates: "/usr/local/filebeat-setup-dashboards"
  register: output
  failed_when: output.rc != 0
  changed_when: False
  tags:
    - debugging

- name: start filebeat
  service:
    name: filebeat
    state: started
    enabled: true


# END Filebeat
################################################################################

################################################################################
# BEGIN Journalbeat
- name: install journalbeat
  yum:
    name: "journalbeat"
    state: present

- name: configure journalbeat
  template:
    src: "journalbeat.yml.j2"
    dest: "/etc/journalbeat/journalbeat.yml"
  notify: restart journalbeat

- name: setup journalbeat
  shell: "journalbeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['localhost:9200'] setup.kibana.host={{kb_server_host}}:5601 && touch /usr/local/journalbeat-setup"
  args:
    creates: "/usr/local/journalbeat-setup"
  register: output
  failed_when: output.rc != 0
  changed_when: False

- name: setup journalbeat templates
  shell: "journalbeat setup --template -E output.logstash.enabled=false -E output.elasticsearch.hosts=['localhost:9200'] setup.kibana.host={{kb_server_host}}:5601 && touch /usr/local/journalbeat-setup-templates"
  args:
    creates: "/usr/local/journalbeat-setup-templates"
  register: output
  failed_when: output.rc != 0
  changed_when: False

- name: start journalbeat
  service:
    name: journalbeat
    state: started
    enabled: true


# END Filebeat
################################################################################
