---

################################################################################
# BEGIN Prereqs
- name: install elastic rpm key
  rpm_key:
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: install prereqs
  yum:
    name:
      - "java-1.8.0-openjdk"
      - "httpd"
      - "httpd-tools"
    state: present

# END Prereqs
################################################################################

################################################################################
# BEGIN Elasticsearch
- name: install elasticsearch
  yum:
    name: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{elk_version}}.rpm"
    state: present

- name: sysconfig elasticsearch
  copy:
    src: "elasticsearch.sysconf"
    dest: "/etc/sysconfig/elasticsearch"
  notify: restart elasticsearch

- name: configure elasticsearch
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
  notify: restart elasticsearch

- name: start and enable elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true
# END Elasticsearch
################################################################################


################################################################################
# BEGIN Logstash
- name: install logstash
  yum:
    name: "https://artifacts.elastic.co/downloads/logstash/logstash-{{elk_version}}.rpm"
    state: present

- name: start logstash
  service:
    name: logstash
    state: started
    enabled: true
# END Logstash
################################################################################


################################################################################
# BEGIN Kibana
- name: install kibana
  yum:
    name: "https://artifacts.elastic.co/downloads/kibana/kibana-{{elk_version}}-x86_64.rpm"
    state: present

- name: configure kibana
  template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
  notify: restart kibana

- name: start kibana
  service:
    name: kibana
    state: started
    enabled: true

- name: allow port 5601
  firewalld:
    port: 5601/tcp
    state: enabled
    permanent: true
    immediate: true
# END Kibana
################################################################################
